### ISSUE TITLE
Web build failed when rbfx is in a subdirectory

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [rokups/rbfx#109]
https://github.com/rokups/rbfx/issues/103

Hi, VS build works now but unfortunately web build are still failing. 
I think the cause might be urho's CXX_FLAGS (and also compile flags set by EASTL target) not propagating to the final project.
*linked using target_link_libraries and modified version of add_sample macro (only variable renaming and make bin dir fixed relative to urho folder)

at final project, 
```CXX_FLAGS = -g -fPIE   -Wno-literal-suffix -Wno-invalid-offsetof -Oz -DNDEBUG -O3 --memory-init-file 0 -g4```
at urho's source folder
```CXX_FLAGS =  -Wno-warn-absolute-paths -Wno-unknown-warning-option -std=gnu++17 -g -DURHO3D_DEBUG -fPIE   -Wno-literal-suffix -Wno-invalid-offsetof -Oz -DNDEBUG -O3 --memory-init-file 0 -g4```

CXX_FLAGS of the build-in sample is the same as urho's, as expected (btw copying sample out to folder sample outside also produce the same error)

also, setting target_set_property directly doesn't appears to change the flag.
Any ideas what might be causing this?

**Comment by rokups** [comment]
Could you make a minimal git repo reproducing issue so i could play with it?

**Comment by UNDEFINED-BEHAVIOR** [comment]
https://github.com/UNDEFINED-BEHAVIOR/rbfx-scaffold/tree/tmp/webbuildfail
here
its using modified rbfx tho (to accept the latest sdl) but should keep up main rbfx.

cmake config command used
```cmake \
.. \
-DCMAKE_TOOLCHAIN_FILE=../dep/internal/rbfx/CMake/Toolchains/Emscripten.cmake \
-DCMAKE_CXX_STANDARD=17 \
-DCMAKE_BUILD_TYPE=Debug \
-DURHO3D_CSHARP=0 \
-DURHO3D_SAMPLES=0 \
-DURHO3D_NAVIGATION=0 \
-DURHO3D_IK=0 \
-DURHO3D_PHYSICS=0 \
-DURHO3D_WEBP=0 \
-DEMSCRIPTEN_WASM=0 \
-DEMSCRIPTEN_AUTO_SHELL=1 \
-DEMSCRIPTEN_SHARE_DATA=1 \
-DURHO3D_NO_PLAYER=1 \
-DURHO3D_LIB_TYPE=STATIC \
-DEMSCRIPTEN_EMRUN_BROWSER=firefox \
-DEMSCRIPTEN_MEMORY_GROWTH=0 \
-DEMSCRIPTEN_MEMORY_LIMIT=512```

**Comment by rokups** [comment]
And in what environment are you building?

**Comment by UNDEFINED-BEHAVIOR** [comment]
wsl, emscripten sdk-incoming-64bit

**Comment by UNDEFINED-BEHAVIOR** [comment]
oops forgot to push the merge to fork https://github.com/UNDEFINED-BEHAVIOR/rbfx, please update

About tracy-profiler, does it depend on some application project getting build first? I've been getting this error again if I tried to build tracy-profiler first on a new project, but went fine if some application project were build first.
https://user-images.githubusercontent.com/8407331/60764351-11d8d280-a0c3-11e9-8418-d90c106054ff.png

**Comment by rokups** [comment]
Ok first of all `-DURHO3D_LIB_TYPE=STATIC` is not in use. Set standard cmake variable `-DBUILD_SHARED_LIBS=ON/OFF` to enable building shared/static libraries.

`-DURHO3D_NO_PLAYER=1` is also not in use since rbfx has totally different player and it is very much work in progress still.

As for actual problem - it seems that `CMAKE_CXX_STANDARD` does not properly propagate to projects when built with emscripten. I have a workaround in works. Once builds pass i will commit it. Should be happening in about 8 hours. If you want to peek at it earlier - https://github.com/rokups/rbfx/tree/rk-develop/. Keep in mind this is my WIP branch which i constantly overwrite so dont depend on it to be consistent.

**Comment by UNDEFINED-BEHAVIOR** [comment]
Thanks I will take a look at it.
