### ISSUE TITLE
D3D11 GPU profiling support

### ISSUE THREAD

**Issue by rokups** [rokups/rbfx#110]
Should get https://bitbucket.org/Nukem9/tracy/commits/227d3e9d2b1518031af9fb0114abd37a3f7d4f7f merged to tracy so rbfx can use GPU profiling on D3D11.

**Comment by bvanevery** [comment]
Current build with only URHO_CSHARP selected.  When trying to run Editor, it fails with a dialog box:
>Tracy profiler initialization failure
>CPU doesn't support RDTSCP instruction

If looking for motive to pull newer Tracy, this is one.  My laptop is old.  Tracy is presumably making unwarranted assumption that RDTSCP instruction is available at runtime, instead of just RDTSC.  Unless rbfx was supposed to use a function to test for RDTSCP availability before calling something.

**Comment by bvanevery** [comment]
https://bitbucket.org/wolfpld/tracy/issues/51/visual-studio-2019-clang-issues
An invalid issue referring to an undesired __rdtscp intrinsic, involving VS 2019 and Clang.  Some dev was being lazy and filed an issue instead of fixing his own problem in the obvious way, by updating Tracy:

> This occurs in three locations, on my slightly outdated Tracy version (I know, I should really update but I don’t have the time to update right now) it’s on line 104 and line 125 in TracyProfiler.hpp, and line 358 in TracyProfiler.cpp. 

But hey at least his report might be relevant for someone else who comes along.  :-)

**Comment by bvanevery** [comment]
rbfx TracyVersion.hpp yields 0.5.11.  This is 1 minor and 4 patch releases behind official releases, if the author actually follows a "major minor patch" numbering culture.  
https://github.com/wolfpld/tracy/blob/master/NEWS
>v0.5 (2019-08-10)
> v0.6 (2019-11-17)
> v0.6.1 (2019-11-28)
> v0.6.2 (2019-12-30)
> v0.6.3 (2020-02-13)
> v0.7 (xxxx-xx-xx)

The pace and feature changes of "patch" releases are alarming, particularly v0.6.3.  "Active development", not a focus on stability of a "patch" release.

Rokas, you are listed as a contributor in the docs.
>Rokas Kupstys <rokups@zoho.com> (compatibility fixes, initial CI work, MingW support)

**Comment by rokups** [comment]
Implemented in upstream tracy, can be consumed by including `tracy/TracyD3D11.hpp`.
