### ISSUE TITLE
SDL_MaximizeWindow() internal bug?

### ISSUE THREAD

**Issue by MonkeyFirst** [rokups/rbfx#190]
hi!

I dunno but i'm started thinking that I'm only one who faced with this bug(

better than thousand words - video

https://youtu.be/5ivJosYVz4s

using: last master, win10, vs2071

**Comment by rokups** [comment]
Since assertion triggers it seems like execution never reaches `initialized_ = true;`. Could you look into it some more? Sure there isnt some odd memory corruption thing happening? There literally is no way that this call would prevent engine from initializing. Tell us more about any modifications you may have done or anything else that comes to mind. Try placing a breakpoint on `graphics->Maximize();` and stepping until end of function, see if execution reaches that. Try to put memory breakpoint on `initialized_` and see what changes it.

**Comment by MonkeyFirst** [comment]
ok I made a new one more detailed video, here is https://youtu.be/g7saf638Gu8
it's lastest master, I'm do not do anything with it. 
exept one, I've added MyProject into C:\rbfx\Source\Tools\MyProject dir, but it's not related to editor, that's all. it's just easiest way to create game project

**Comment by rokups** [comment]
That is very odd. Could you please place a breakpoing on `assert(initialized_);` in `RunFrame()` and show me callstack when breakpoint hits?

**Comment by MonkeyFirst** [comment]
yes of course
![123](https://user-images.githubusercontent.com/9577466/74089030-5dc37e00-4acf-11ea-99d1-9fa81890a784.jpg)

**Comment by rokups** [comment]
Thanks. That is enough info, I will look into it.
