### ISSUE TITLE
$prefix\include\Urho3D\ThirdParty\entt\config\{config.h,version.h} are missing on install

### ISSUE THREAD

**Issue by faesong** [rokups/rbfx#202]
I had to manually copy them to build my project using import targets (copying initial info from #201):

When building a project on Windows with Visual Studio 19  using cmake import, which looks like this:

    include ("${RBFX_PREFIX}/share/CMake/Urho3D.cmake")

    add_executable(my_proj
      SRCS...)

    target_link_libraries(my_proj Urho3D)

(rbfx was installed into this ${RBFX_PREFIX} folder by building INSTALL target in VS)

// end of copied part

I suspect the problem is in Source\ThirdParty\entt\CMakeLists.txt (line 27)

    install (DIRECTORY src/ DESTINATION ${DEST_THIRDPARTY_HEADERS_DIR}/ FILES_MATCHING PATTERN *.hpp)

only *.hpp, and no *.h files are installed

**Comment by rokups** [comment]
Both issues resolved. Thank you for testing SDK install. It gets little attention because new build system is focused on allowing user to easily build engine as a dependency. You might want to test this as well.

Consider following dir tree:
```
.
├── my-project
│   ├── CMakeLists.txt
│   └── .git
└── rbfx
    ├── CMakeLists.txt
    └── .git
```

In `my-project/CMakeLists.txt` you can do: `add_subdirectory(../rbfx ${CMAKE_BINARY_DIR}/rbfx)`.
This way you get to build engine from source (and modify it as you like easily) while not pulling it into directory tree or git history of your main project.

**Comment by faesong** [comment]
I try to make it efficient and assume that I need to link multiple projects with one build of the engine, but this:

> ... (...modify it as you like easily) ...

now make me think a bit.

I still will try to keep it all efficient, but having option to do add_subdirectory() is a huge thing actually.

Worth adding that to wiki, as somehow this thought have passed me :)
