### ISSUE TITLE
How to compile this editor?

### ISSUE THREAD

**Issue by zhouxs1023** [rokups/rbfx#70]
I love this editor very much,
I used win7 + vs2015 compile this project ,but can not find engine editor? can you help me how to compile this engine editor? is this project need NET 4.7 ?

**Comment by rokups** [comment]
If you run `Makefile.cmd` found in repository root you should get default build configuration that includes tools (so editor too) and C# support. C# requires .net 4.6+ (older versions may work but are untested).

Note: You may get build errors when compiling engine for the first time because visual studio does not pick up generated bindings code properly. In that case restart VS and compile again.

**Comment by rokups** [comment]
Did you manage to solve your issue?

**Comment by zhouxs1023** [comment]
successfully compiler,but run exe is  crash
