### ISSUE TITLE
CMake Gui build: SN could not be found

### ISSUE THREAD

**Issue by vutle** [rokups/rbfx#75]
What is the correct way to build on windows 10? 

I use CMake gui but get the sn coild not be found error.  
What is SN?

Best regards.

**Comment by rokups** [comment]
`sn.exe` is used for generating signing key for C# binaries. Make sure you have relevant C# tools installed. For starters make sure you have `sn.exe` somewhere in your visual studio installation.

**Comment by vutle** [comment]
![image](https://user-images.githubusercontent.com/6241928/54073350-4afe6300-42da-11e9-8b0a-2d6e22f95194.png)

Thanks manage to get cmake create vs build.
By the way what are these 6 errors when build the projects and samples?

![image](https://user-images.githubusercontent.com/6241928/54073370-6bc6b880-42da-11e9-9789-2f70fdf001dd.png)

**Comment by rokups** [comment]
To change renderer set cmake parameter `URHO3D_RENDERER` to `D3D11`, `D3D9` or `OPENGL`.

To fix nuget errors do restore with msbuild directly: `msbuild Urho3D.sln /t:restore`. All because nuget is a broken piece of camel dung and behaves differently depending on how you invoke it. All nuget-related commands should be executed through `msbuild.exe`.

**Comment by vutle** [comment]
Thank all is working.
Do you have a tutorial to use C# plugins? For real time debugging? Use it like compile script?

**Comment by rokups** [comment]
Not quite. General workflow is pretty simple though.

1. Add a plugin project (like 104_CSharpPlugin sample)
2. Run editor in a debugger
3. Load your plugin in editor `Project` menu
4. Put a breakpoint in your plugin and it will be hit.

To hot-reload you plugin you just need to recompile it. Editor does not need to restart.

Disclaimer: dragons be here.

Visual Studio is stupid in this regard. It insists on stopping debugging in order to build stuff. Nothing i can do about that.

Also do not be surprised if things crash/fail/vaporize your dog. You are treading in a little-tested waters. Should you face any issues - please report :)

**Comment by vutle** [comment]
Thanks Mate,
I will try follow those 4 steps.

By the way. 
Do you have any note on how to properly use the editor?
I created a scene. But when I click on editorSceneSetting I get the error!

![image](https://user-images.githubusercontent.com/6241928/54073886-666c6c80-42e0-11e9-8ac3-10c5328036aa.png)

**Comment by rokups** [comment]
Well that should definitely not happen :trollface: 

I am unable to reproduce issue myself. Please share exact steps how you triggered this.
