### ISSUE TITLE
A quick summary of major difference from urho3d since the split a few years ago?

### ISSUE THREAD

**Issue by UNDEFINED-BEHAVIOR** [rokups/rbfx#90]
Aside from obvious new third party module and the editor.

**Comment by rokups** [comment]
Hey, thanks for taking interest :) I wrote a page of things i managed to remember. Couple may be missing, but hopefully nothing of importance.

[rbfx and Urho3D differences](/rokups/rbfx/wiki/rbfx-and-Urho3D-differences)

**Comment by UNDEFINED-BEHAVIOR** [comment]
Thanks! 

Actually there's still some design decisions I wanted to learn more about:
1. Why was eastl introduced in place of urho's string/containers, and also instead of any other game oriented libraries out there? was it objectively better?
2. Context now holds a few cached pointer to a few other subsystems. And also now friend with Engine class. Was this necessary?

(I was trying to backport rbfx editor back in to vanilla urho3d but there were more breaking changes in urho engine than expected, and are now going back and forth between continuing or just straight up adopt rbfx. So this will help a lot.)

**Comment by rokups** [comment]
> Why was eastl introduced in place of urho's string/containers, and also instead of any other game oriented libraries out there? was it objectively better?

EASTL is maintained (at EA's own pace anyway) and more tested than urho's custom containers. Besides it implements stl so previous knowledge of stdlib is applicable. It also does SBO in multiple places so we are looking into way less allocations by using `easlt::string` alone. I am not aware of another as complete stl implementation as eastl (well maybe stlport, but it is long unmaintained by now). With esatl we also get a predictable performance across platforms, something we cant count on when using stl implementations that come with compilers. There are some pretty cool optimizations geared towards games too. Its just perfect for our usecase.

> Context now holds a few cached pointer to a few other subsystems. And also now friend with Engine class. Was this necessary?

Not really necessary. I did this for my own convenience and to avoid hashmap lookups every time we get a pointer of common subsystem. It is true that hashmap lookup is cheap, but lookup we dont do is even cheaper still ;) As for friend - it is not necessary yes. It is a leftover from earlier developments. Ill get rid of it.

> I was trying to backport rbfx editor back in to vanilla urho3d but there were more breaking changes in urho engine than expected

If you really want to do that you can use source code from a month or few back where it used old urho3d containers. That would make porting significantly easier, but not trivial still. You would also be looking into maintaining editor yourself and getting updates from rbfx would be increasingly difficult as time goes on due to lots of changes between two codebases.

**Comment by UNDEFINED-BEHAVIOR** [comment]
`99a64dd - friendship ended with engine` 
Oh okay
